### ISSUE TITLE
Add IDE and text editor suggestions as a !r command

### ISSUE THREAD

**Issue by Zenoix** [beginnerpy-com/beginner.py-bot#20]
Possibly have a list of IDEs and text editors for people wondering what they should use. Could also categorise them into difficulty levels such as IDLE as easy, pycharm as advanced etc. 

Heruk suggested `!r editor` or `!r ide` as possible commands

Possible links:
- IDLE included with python
- VS code https://code.visualstudio.com/download or https://code.visualstudio.com/learntocode (vscode setup automatically for python)
- Sublime https://www.sublimetext.com/3
- Pycharm https://www.jetbrains.com/pycharm/download/#section=windows
- Jupyter notebook/lab https://www.anaconda.com/products/individual

**Comment by ZechCodes** [comment]
Sounds like a good idea to me. Could do categories like basic, extensible, & integrated. How difficult an editor is depends more on familiarity.

**Comment by Zenoix** [comment]
We have a tip for this now so Imma close this issue.
